version: 2
jobs:
  test:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
